# Dependencies
gems: [jekyll-paginate]

markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            gg
tagline:          'Î»'
description:      ''
url:              http://garciat.com
baseurl:          '/'
google_analytics: 'UA-19283098-3'

author:
  name:           'Gabriel Garcia'
  url:            https://github.com/Garciat

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/Garciat
