# Site settings
title: Gabriel Garcia
author: Gabriel Garcia
baseurl: ""
url: "http://localhost:4000"
google_analytics: "UA-19283098-3"

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
permalink: pretty
paginate: 3
