# Dependencies
gems:
  - jekyll-paginate
  - jekyll-redirect-from

markdown:         kramdown
highlighter:      rouge

# Permalinks
collections:
  posts:
    output: true
    permalink: /:collection/:title

# Setup
title:            gg
tagline:          'Î»'
description:      ''
url:              http://garciat.com
google_analytics: 'UA-19283098-3'

author:
  name:           'Gabriel Garcia'
  url:            https://github.com/Garciat

paginate:         15

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/Garciat
