name: Build site

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build GitHub Pages with Lume
        uses: Garciat/lumeland-build/gh-pages@garciat
        with:
          deno-version: v2.x

      - name: Publish to WebSubHub
        run: |
          curl -X POST -d "hub.mode=publish&hub.url=https://garciat.com/posts.rss" https://websubhub.com/hub
          curl -X POST -d "hub.mode=publish&hub.url=https://garciat.com/posts.json" https://websubhub.com/hub
